#!/bin/sh
# ─── docker-entrypoint.sh — tg-ticket-monitor ───────────────────────────
#
# Writes env vars into .env so that python-dotenv (loaded by bot.py)
# can find them, then runs the bot.
#
# Supported env vars:
#   BOT_TOKEN   (required) — Telegram bot token
#

set -e

# ── Generate .env from environment ──────────────────────────────────────
echo "# Generated by docker-entrypoint.sh — do not edit" > .env

if [ -n "$BOT_TOKEN" ]; then
    echo "BOT_TOKEN=${BOT_TOKEN}" >> .env
else
    echo "ERROR: BOT_TOKEN environment variable is not set."
    echo "Pass it with:  -e BOT_TOKEN=your_token_here"
    exit 1
fi

# ── Run the bot ─────────────────────────────────────────────────────────
exec python3 bot.py
